### ISSUE TITLE
Implementation of the trace of a finite element

### ISSUE THREAD

**Issue by thomasgibson** [FInAT/FInAT#29]
This is mainly for the record and discussion. Currently, the trace element is only implemented in FIAT, but it seems that FInAT is probably a better framework to implement a wide range of trace elements. Such elements could include the following:

- The trace of an HDiv-conforming element: a DG facet field (implemented in FIAT as `HDivTrace`) used in hybrid-mixed methods for RT/BDM discretizations, and arises in some DG formulations.

- The trace of an H1-conforming element: a CG facet field, which is useful for more general static condensation methods.

- The trace of an HCurl-conforming element: an edge-field space. This is probably not going to be needed anytime soon, but would be nice for those wanting to hybridize HCurl methods. This may require additional changes to code generation and introducing a new measure in UFL (`de` for edge integrals)

**Comment by connorjward** [comment]
Closing as replaced by https://github.com/firedrakeproject/fiat/issues/113
