### ISSUE TITLE
Oracle/UFL registration

### ISSUE THREAD

**Issue by rckirby** [FInAT/FInAT#75]
Supposing we are ok with FInAT depending on UFL, what needs to happen for FInAT to directly register its elements with UFL so that we can get rid of the `finat_interface` business in TSFC and allow new elements to be added only to FI(n)AT + any Firedrake-level tests?  This would eliminate the need for PRs to UFL and TSFC and make it easier to add new elements.

Partial discussions have been held in ephemeral locations (e.g. slack), but the can be a more permanent/visible thread for the discussions among interested parties.

**Comment by ReubenHill** [comment]
#1971 , which creates a whole element in firedrake, may be relevant here.

**Comment by rckirby** [comment]
I like that, it could be relevant.  But the tsfc `finat_interface.py` is a bit more complicated than just point-to-point between UFL and FInAT names.  We would to mover over the whole `convert` single dispatch business that catches tensor products, broken elements, variants business.

**Comment by ReubenHill** [comment]
There's now a dirty hack of TSFC's convert single dispatch in https://github.com/firedrakeproject/firedrake/pull/1971

**Comment by miklos1** [comment]
I don't like the idea of FInAT (or anyone else; but for testing it is okay.) registering UFL elements.  UFL should be an implementation-independent interface, which could be shared between Firedrake, FEniCS, DUNE, and possibly everyone else.  When you let the implementation extend the interface, then you practically diversify the interface: there will be pure UFL, and UFL extended with FInAT.  If others start doing the same, then the UFL ecosystem might end up having different names for the same element, depending on implementation.  This would weaken UFL as a single interface that could be shared by different projects.

However, I have no objection against moving `tsfc.finatinterface` to FInAT, which could then eliminate one pull request when a new element is added (i.e. the TSFC pull request).  But I wish that the UFL dependecy of FInAT be optional, similarly to Firedrake citations, you have the extra functionality if UFL is available, but if not, you be still able to use FInAT without it.

**Comment by wence-** [comment]
> I don't like the idea of FInAT (or anyone else; but for testing it is okay.) registering UFL elements. UFL should be an implementation-independent interface, which could be shared between Firedrake, FEniCS, DUNE, and possibly everyone else. When you let the implementation extend the interface, then you practically diversify the interface: there will be pure UFL, and UFL extended with FInAT. If others start doing the same, then the UFL ecosystem might end up having different names for the same element, depending on implementation. This would weaken UFL as a single interface that could be shared by different projects.
> 
> However, I have no objection against moving `tsfc.finatinterface` to FInAT, which could then eliminate one pull request when a new element is added (i.e. the TSFC pull request). But I wish that the UFL dependecy of FInAT be optional, similarly to Firedrake citations, you have the extra functionality if UFL is available, but if not, you be still able to use FInAT without it.

The thing that really lives in UFL is the _name_ of the element (nothing more). So the question is whether there should be a fully-canonical registry of element names (and if so where it should live).

Then there are different element libraries that can advertise that they implement a given name.

I agree that the current code that lives in tsfc that converts UFL elements into finat equivalents can migrate (and should be conditionally enabled).

**Comment by miklos1** [comment]
> The thing that really lives in UFL is the _name_ of the element (nothing more). So the question is whether there should be a fully-canonical registry of element names (and if so where it should live).
> 
> Then there are different element libraries that can advertise that they implement a given name.

In most cases, it is just the name, in some cases there are variants, such as a CG elements can be equispaced, GLL, or whatever other options there are.

What I think really should be avoided, is that the very same thing must be called differently depending on the implementation.  

I think it is tolerable, if the same code behaves slightly differently depending on the implementation, such as you ask for the high-order CG element without explicitly specifying a variant, and one implementation tries to be smart and gives you a spectral continuous element by default, while another only has equispaced elements, so they give you just that.

**Comment by connorjward** [comment]
Closing as replaced by https://github.com/firedrakeproject/fiat/issues/111
