### ISSUE TITLE
Can't create PointSet.expression for when have empty points list

### ISSUE THREAD

**Issue by ReubenHill** [FInAT/FInAT#78]
Running this code results in the following error
```python
from finat.point_set import PointSet
import numpy as np

# This is a valid point set at the moment - e.g. for P0DG on a vertex
# which, in FIAT, defines the reference cell as being at an empty tuple
# point and so gives a dual.pt_dict of {(): [(1.0, ())]}.
# This can be seen happening in tsfc/driver.py lines 362-369.
points = [()]
# Can create a PointSet
ps = PointSet(points)
# Have 0 points
assert ps.points.shape == np.array([[]]).shape
# This errors when trying to make expression using
# gem.partial_indexed(gem.Literal(self.points), self.indices)
ps.expression
```

```
  File "FInAT_issue.py", line 15, in <module>
    ps.expression
  File "/Users/rwh10/firedrake/src/tsfc/gem/utils.py", line 19, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/rwh10/firedrake/src/FInAT/finat/point_set.py", line 75, in expression
    return gem.partial_indexed(gem.Literal(self.points), self.indices)
  File "/Users/rwh10/firedrake/src/tsfc/gem/gem.py", line 882, in partial_indexed
    return ComponentTensor(
  File "/Users/rwh10/firedrake/src/tsfc/gem/gem.py", line 48, in __call__
    obj = super(NodeMeta, self).__call__(*args, **kwargs)
  File "/Users/rwh10/firedrake/src/tsfc/gem/gem.py", line 654, in __new__
    assert all(shape)
```

This clearly raises some questions about what the `PointSet.expression` should be, nevertheless the fact that you can make such a `PointSet` suggests the `.expression` should be accessible.

**Comment by wence-** [comment]
This is a corner case that has not previously been considered I suppose. What do we need this to say so that on the outside you don't need to special case?

**Comment by wence-** [comment]
⊥ is always problematic in any type system :)

**Comment by ReubenHill** [comment]
`PointSingleton` is kind of set up for dealing with this and returns `Zero((0,))` for `.expression` with `()` as the initial `point`. We could consider extending the use of it to `compile_expression_dual_evaluation` and either 
 - (a) disallow creating a `PointSet` for "zero" points (i.e. `points = [()]`) or
 - (b) return a `PointSingleton` when you create a `PointSet` with `points = [()]` points.

**Comment by ReubenHill** [comment]
or 
 - (c) detect in `PointSet` if there are "zero" points and return `gem.Literal(self.points)` as happens in `PointSingleton`

**Comment by wence-** [comment]
We're using `()` to indicate "unit", a point with no values. I don't think there's any way we can represent a point with no values using `gem.Literal`. `Zero((0,))` is clearly wrong for a point `()`, it's equivalent to `(0,)`.

What can you do with the point `()`? How does it need to behave in expressions so that you don't have to special case outside?

**Comment by ReubenHill** [comment]
In the case I give, it's also a point with no "location" on the reference cell since we're in 0D. It's a design decision we made in https://github.com/FEniCS/fiat/pull/41/ . 

Clearly GEM takes a different view and automatically gives `Zero((0,))` for `gem.Literal(numpy.array([]))`

**Comment by ReubenHill** [comment]
See #79 for suggested fix

**Comment by miklos1** [comment]
File "/Users/rwh10/firedrake/src/tsfc/gem/gem.py", line 654, in __new__
        assert all(shape)

Based on your stacktrace, what happens is `ComponentTensor` refuses to be created because it has degenerate shape, e.g. one of its extents is zero.

>     * (a) disallow creating a `PointSet` for "zero" points (i.e. `points = [()]`) or

We must be careful with terminology for clarity; `points = [()]` is clearly one 0-dimensional point and not zero points in the sense of no points.

> Clearly GEM takes a different view and automatically gives `Zero((0,))` for `gem.Literal(numpy.array([]))`

This is because `numpy.array([])` has shape `(0,)`.

**Comment by ReubenHill** [comment]
> We must be careful with terminology for clarity; `points = [()]` is clearly one 0-dimensional point and not zero points in the sense of no points.
> 
> >

Yes you are right - and a single 0-dimensional point is exactly what it's supposed to represent in this context so glad that's as expected :)



> This is because `numpy.array([])` has shape `(0,)`.

So, in your view, is `Zero((0,))` the correct expression for a single dimensional point?

**Comment by miklos1** [comment]
> So, in your view, is `Zero((0,))` the correct expression for a single dimensional point?

I think so.  A point, generally speaking, is a vector (tensor of rank 1).  A 0-dimensional point then should be a vector of length zero, so its shape ought to be `(0,)`.

**Comment by ReubenHill** [comment]
Okay so here we have
```python
gem.partial_indexed(gem.Literal(self.points), self.indices)
```
where 
 - `self.points` is `array([], shape=(1, 0), dtype=float64)`
 - `self.indices` is `(Index(1),)` with `self.indices[0].extent` being 1
 - `gem.Literal(self.points)` is `Zero((1, 0))` with `gem.Literal(self.points).shape` being `(1, 0)`

Does all this look correct to you such that we have valid arguments for `gem.partial_indexed`? 

If so it points to a problem with tsfc as you suggested in #79 .

**Comment by ReubenHill** [comment]
I note that, in [here in tsfc](https://github.com/firedrakeproject/tsfc/blob/e6d0fa8a4337a82f78b8ca9934200041c2080059/gem/gem.py#L883) we end up doing `Indexed(Zero((1, 0)), indices + shape_indices)` giving us `Zero(())` which has no free indices - I.e. the indices are dropped.

Is this correct? I recall previous discussions about indices and shape not being "conservative".

**Comment by miklos1** [comment]
> Okay so here we have
> 
> ```python
> gem.partial_indexed(gem.Literal(self.points), self.indices)
> ```
> 
> where
> 
>     * `self.points` is `array([], shape=(1, 0), dtype=float64)`
> 
>     * `self.indices` is `(Index(1),)` with `self.indices[0].extent` being 1
> 
>     * `gem.Literal(self.points)` is `Zero((1, 0))` with `gem.Literal(self.points).shape` being `(1, 0)`
> 
> 
> Does all this look correct to you such that we have valid arguments for `gem.partial_indexed`?

The shapes and index extents certainly match, and unless the disappearing running index troubles us, the result should be `Zero((0,))`.  If the disappering index is troubling, why don't you just use a `PointSingleton` in the first place, that way you don't have a disappearing point index to begin with?

**Comment by wence-** [comment]
> Is this correct? I recall previous discussions about indices and shape not being "conservative".

Scalars implicitly broadcast (recall previous discussions about dual evaluation). So `Indexed(Zero, ...)` is always simplified to `Zero`.

**Comment by ReubenHill** [comment]
Okay so getting rid of [this assertion in `ComponentTensor`](https://github.com/firedrakeproject/tsfc/blob/e6d0fa8a4337a82f78b8ca9934200041c2080059/gem/gem.py#L654) causes this to return `Zero((0,))` as expected.

What is the underlying reason for that assertion? What mistake is it trying to catch? I'm wondering if I should just move it to [after the Zero folding in ComponentTensor](https://github.com/firedrakeproject/tsfc/blob/e6d0fa8a4337a82f78b8ca9934200041c2080059/gem/gem.py#L656-L658).

**Comment by miklos1** [comment]
So what I would try first, is to use `PointSingleton(())` instead of `PointSet([()])`.  If that is somehow not feasible, and the disappearing index is still annoying, perhaps one could consider not reducing degenerate `Literal`s to `Zero`s.  (Is a 1 x 0 matrix a null matrix?  In some way certainly is...)

**Comment by miklos1** [comment]
> Okay so getting rid of [this assertion in `ComponentTensor`](https://github.com/firedrakeproject/tsfc/blob/e6d0fa8a4337a82f78b8ca9934200041c2080059/gem/gem.py#L654) causes this to return `Zero((0,))` as expected.
> 
> What is the underlying reason for that assertion? What mistake is it trying to catch?

I probably wasn't thinking of zero extents, so the most likely explanation is to catch `None`s which are also false in Python.  For convenience, running indices are creating with `None` as extent, and then this is set when they are first used to index something.  `ComponentTensor(Zero(), (Index(), Index()))` would otherwise create a tensor with shape `(None, None)`, and we probably don't want that.

**Comment by wence-** [comment]
> Okay so getting rid of this assertion in ComponentTensor causes this to return Zero((0,)) as expected.

I would have thought that `all(s >= 0 for s in shape)` is probably a more valid assertion?

**Comment by miklos1** [comment]
> I would have thought that `all(s >= 0 for s in shape)` is probably a more valid assertion?

I agree that this better reflects the probable original intent.

**Comment by ReubenHill** [comment]
Great! I've made https://github.com/firedrakeproject/tsfc/pull/246 to try and deal with this

**Comment by ReubenHill** [comment]
Closing since actually a TSFC issue which is resolved by https://github.com/firedrakeproject/tsfc/pull/246.
