### ISSUE TITLE
QuadratureElement is not comparing the cell and quadrature dimensions correctly

### ISSUE THREAD

**Issue by pbrubeck** [FInAT/FInAT#90]
Suppose I want to define a FunctionSpace with a Quadrature element on a hexahedral mesh:
```python
from firedrake import *
mesh = ExtrudedMesh(UnitSquareMesh(1,1,quadrilateral=True),layers=1)
Qe = FiniteElement("Quadrature", mesh.ufl_cell(), degree=3, quad_scheme="default")
Q = FunctionSpace(mesh, Qe)
```
The snippet above gives the following error:
```
~/firedrake-dev-20200825-mpich/src/FInAT/finat/quadrature_element.py in __init__(self, fiat_ref_cell, rule)
     44             raise TypeError("rule is not an AbstractQuadratureRule")
     45         if fiat_ref_cell.get_dimension() != rule.point_set.dimension:
---> 46             raise ValueError("Cell dimension does not match rule's point set dimension")
     47         self._rule = rule
     48 
ValueError: Cell dimension does not match rule's point set dimension
```

This is because the cell dimension comes out as a tuple:
```
(Pdb++) fiat_ref_cell.get_dimension()
(2, 1)
(Pdb++) rule.point_set.dimension
3
```

**Comment by dham** [comment]
I think you need to make a tensor product quadrature element out of a quad quadrature element and an interval quadrature element. This is what happens behind the scenes if you ask for, e.g. P1 on a hex mesh. We clearly haven't wired up quadrature element to do it for you.

**Comment by ReubenHill** [comment]
Is this resolved @pbrubeck ?

**Comment by pbrubeck** [comment]
Sorry, not yet. What I have done as a workaround is to reduce the tuple cell dimension to a single int via additon, but as @dham suggests, the proper fix needs to modify the way  `FiniteElement` in Firedrake constructs `QuadratureElements` on TP cells.

**Comment by wence-** [comment]
> I think you need to make a tensor product quadrature element out of a quad quadrature element and an interval quadrature element. This is what happens behind the scenes if you ask for, e.g. P1 on a hex mesh. We clearly haven't wired up quadrature element to do it for you.

I wonder if doing this eagerly in the `FiniteElement` constructor is the right thing, or if the `UFL -> FINAT` translation in tsfc should handle it.

I say this because @pbrubeck has hit some snags when wanting to `reconstruct` `FiniteElement` objects with a new degree on tensor product cells. 

For example, if you ask for a `FiniteElement("RTCF", TPC(quadrilateral, interval), 3)` you actually get an `Enriched(HDiv(...), ...)` and trying to reconstruct a lower degree version (via `element.reconstruct(degree=1)` doesn't work. Arguably it's an implementation detail that RTCF is implemented in this structured way. The same for the quadrature element.

**Comment by pbrubeck** [comment]
What about?

```
diff --git a/finat/quadrature_element.py b/finat/quadrature_element.py
index 42c97f9..94e51ed 100644
--- a/finat/quadrature_element.py
+++ b/finat/quadrature_element.py
@@ -12,6 +12,9 @@ from gem.utils import cached_property
 from finat.finiteelementbase import FiniteElementBase
 from finat.quadrature import make_quadrature, AbstractQuadratureRule
 
+from ufl.cell import TensorProductCell
+from ufl.finiteelement.tensorproductelement import TensorProductElement
+
 
 def make_quadrature_element(fiat_ref_cell, degree, scheme="default"):
     """Construct a :class:`QuadratureElement` from a given a reference
@@ -25,8 +28,17 @@ def make_quadrature_element(fiat_ref_cell, degree, scheme="default"):
         "canonical" or "KMV".
     :returns: The appropriate :class:`QuadratureElement`
     """
-    rule = make_quadrature(fiat_ref_cell, degree, scheme)
-    return QuadratureElement(fiat_ref_cell, rule)
+    if isinstance(fiat_ref_cell, TensorProductCell):
+        subcells = fiat_ref_cell.sub_cells()
+        elems = []
+        degrees = degree if len(degree) == len(subcells) else [degree]*len(subcells)
+        for cell, deg in zip(subcells, degrees):
+            rule = make_quadrature(cell, deg, scheme)
+            elems.append(QuadratureElement(cell, rule))
+        return TensorProductElement(*elems)
+    else:
+        rule = make_quadrature(fiat_ref_cell, degree, scheme)
+        return QuadratureElement(fiat_ref_cell, rule)

```

**Comment by pbrubeck** [comment]
> Looking at it, the `make_quadrature` stuff works fine, and it might just be the error checking that is bad.
> 
> Does this patch DTRT?
> 
> ```
> diff --git a/finat/quadrature_element.py b/finat/quadrature_element.py
> index 42c97f9..43d806d 100644
> --- a/finat/quadrature_element.py
> +++ b/finat/quadrature_element.py
> @@ -42,7 +42,7 @@ class QuadratureElement(FiniteElementBase):
>          self.cell = fiat_ref_cell
>          if not isinstance(rule, AbstractQuadratureRule):
>              raise TypeError("rule is not an AbstractQuadratureRule")
> -        if fiat_ref_cell.get_dimension() != rule.point_set.dimension:
> +        if fiat_ref_cell.get_spatial_dimension() != rule.point_set.dimension:
>              raise ValueError("Cell dimension does not match rule's point set dimension")
>          self._rule = rule
>  
> ```

That looks right to me.

**Comment by ReubenHill** [comment]
Yep I agree this patch is correct. From fiat `reference_element.py`:
```python
class Cell(object):
    ...
    def get_dimension(self):
        """Returns the subelement dimension of the cell.  For tensor
        product cells, this a tuple of dimensions for each cell in the
        product.  For all other cells, this is the same as the spatial
        dimension."""
        raise NotImplementedError("Should be implemented in a subclass.")
```

Does the docstring for `AbstractPointSet.dimension` need updating e.g. to state it's always a _geometric_ dimension? Or is that not quite true? It can certainly never be a tuple.

**Comment by wence-** [comment]
It's not a geometric dimension in the sense of "embedding" dimension (since we're on a reference cell here). I think `"point dimension"` is fine.
