### ISSUE TITLE
caching of `PointSet.indices`

### ISSUE THREAD

**Issue by wence-** [FInAT/FInAT#96]
The caching of pointset indices is problematic when used inside the `dual_basis` properties. This would raise its head if one ever made a tensor product of more than one copy of a quadrature element.

One solution would be to refactor such that the pointsets always return fresh indices when queried (like most other finat objects), although now the `expression` property will have to change.

**Comment by connorjward** [comment]
Closing as replaced by https://github.com/firedrakeproject/fiat/issues/108
