### ISSUE TITLE
Unify TensorFiniteElement and FiniteElementBase dual_evaluation

### ISSUE THREAD

**Issue by ReubenHill** [FInAT/FInAT#99]
At the moment all elements use a common `dual_evaluation` method (defined in FiniteElementBase) except for TensorFiniteElement.

The reason for this may be that TensorFiniteElement is 'breaking the promise' about the advertised dual_basis: the Q tensor shape (before indexing out the point set) should go 
```
(basis_indices, point_set_indices, expression_contraction_shape_indices)
```
however at the moment I think TensorFiniteElement advertises 
```
(base_element_basis_indices, point_set_indices, 
 tensor_element_base_index_1, expression_contraction_shape_index_1, 
 ..., 
 tensor_element_base_index_N, expression_contraction_shape_index_N)
```
because we naively multiply by deltas with indices `(tensor_element_base_index_1, expression_contraction_shape_index_1)` ... `(tensor_element_base_index_N, expression_contraction_shape_index_N)` to raise the rank of the Q as necessary.

I think if we reorder the indices via a `ComponentTensor` to
```
(base_element_basis_indices, point_set_indices, 
 tensor_element_base_index_1, ..., tensor_element_base_index_N
 expression_contraction_shape_index_1, ..., expression_contraction_shape_index_N)
```
then make sure we ask for delta elimination we should be able to use the same `dual_evaluation` method as everywhere else.

I might be wrong here of course! I could have the "promise" wrong here - it certainly isn't well described in the documentation.
Note also that we might take this opportunity to change the `dual_basis` API to index out _all_ the contraction indices from Q (not just the point set index).

Thoughts?

**Comment by connorjward** [comment]
Closing as moved over to https://github.com/firedrakeproject/fiat/issues/107
